# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ollama-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 200Gi
#   storageClassName: do-block-storage

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ollama
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ollama
#   template:
#     metadata:
#       labels:
#         app: ollama
#     spec:
#       containers:
#         - name: ollama
#           image: ollama/ollama:latest
#           args: ["server"]
#           ports:
#             - containerPort: 11434
#           volumeMounts:
#             - name: ollama-data
#               mountPath: /root/.ollama
#           resources:
#             requests:
#               cpu: "2"
#               memory: "8Gi"
#             limits:
#               cpu: "8"
#               memory: "32Gi"
#       volumes:
#         - name: ollama-data
#           persistentVolumeClaim:
#             claimName: ollama-pvc
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ollama
# spec:
#   selector:
#     app: ollama
#   ports:
#     - protocol: TCP
#       port: 11434
#       targetPort: 11434
#   type: LoadBalancer